spring:
  application:
    name: backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/luxeloot
    username: peter
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

uploaded:
  folder: d:/AuctionWeb/static/images/

image:
  storage-path: file:///d:/AuctionWeb/static/images/

data:
  seed-data: false
